### PR TITLE
[Feature][ci size] Fix PX

### PR DESCRIPTION
**Pull request by guchito9**

### CODE REVIEW

**Comment by guchito9** [comment]
SIZE REPORT IS:

**Comment by guchito9** [comment]
$(find . -type f -name "*.kt" | xargs du -sh --apparent-size)

**Comment by guchito9** [comment]
holis

**Comment by guchito9** [comment]
environment var (SIZE_REPORT) value too large - rejected

**Comment by guchito9** [comment]
396K	./px-services/build/outputs/aar/services-release.aar
483K	./px-services/build/outputs/aar/services-debugBeta.aar
483K	./px-services/build/outputs/aar/services-debug.aar
57K	./testlib/build/outputs/aar/testlib-debug.aar
57K	./testlib/build/outputs/aar/testlib-debugBeta.aar
52K	./testlib/build/outputs/aar/testlib-release.aar
139K	./px-testlib/build/outputs/aar/testlib-debug.aar
139K	./px-testlib/build/outputs/aar/testlib-debugBeta.aar
123K	./px-testlib/build/outputs/aar/testlib-release.aar
2.9M	./px-checkout/build/outputs/aar/checkout-release.aar
3.1M	./px-checkout/build/outputs/aar/checkout-debug.aar
3.1M	./px-checkout/build/outputs/aar/checkout-debugBeta.aar
58K	./px-addons/build/outputs/aar/addons-debug.aar
50K	./px-addons/build/outputs/aar/addons-release.aar
58K	./px-addons/build/outputs/aar/addons-debugBeta.aar

**Comment by guchito9** [comment]
396K	./px-services/build/outputs/aar/services-release.aar
483K	./px-services/build/outputs/aar/services-debugBeta.aar
483K	./px-services/build/outputs/aar/services-debug.aar
57K	./testlib/build/outputs/aar/testlib-debug.aar
57K	./testlib/build/outputs/aar/testlib-debugBeta.aar
52K	./testlib/build/outputs/aar/testlib-release.aar
139K	./px-testlib/build/outputs/aar/testlib-debug.aar
139K	./px-testlib/build/outputs/aar/testlib-debugBeta.aar
123K	./px-testlib/build/outputs/aar/testlib-release.aar
2.9M	./px-checkout/build/outputs/aar/checkout-release.aar
3.1M	./px-checkout/build/outputs/aar/checkout-debug.aar
3.1M	./px-checkout/build/outputs/aar/checkout-debugBeta.aar
58K	./px-addons/build/outputs/aar/addons-debug.aar
50K	./px-addons/build/outputs/aar/addons-release.aar
58K	./px-addons/build/outputs/aar/addons-debugBeta.aar

**Comment by guchito9** [comment]
396K	./px-services/build/outputs/aar/services-release.aar
483K	./px-services/build/outputs/aar/services-debugBeta.aar
483K	./px-services/build/outputs/aar/services-debug.aar
57K	./testlib/build/outputs/aar/testlib-debug.aar
57K	./testlib/build/outputs/aar/testlib-debugBeta.aar
52K	./testlib/build/outputs/aar/testlib-release.aar
139K	./px-testlib/build/outputs/aar/testlib-debug.aar
139K	./px-testlib/build/outputs/aar/testlib-debugBeta.aar
123K	./px-testlib/build/outputs/aar/testlib-release.aar
2.9M	./px-checkout/build/outputs/aar/checkout-release.aar
3.1M	./px-checkout/build/outputs/aar/checkout-debug.aar
3.1M	./px-checkout/build/outputs/aar/checkout-debugBeta.aar
58K	./px-addons/build/outputs/aar/addons-debug.aar
50K	./px-addons/build/outputs/aar/addons-release.aar
58K	./px-addons/build/outputs/aar/addons-debugBeta.aar

**Comment by guchito9** [comment]
396K	./px-services/build/outputs/aar/services-release.aar
483K	./px-services/build/outputs/aar/services-debugBeta.aar
483K	./px-services/build/outputs/aar/services-debug.aar
57K	./testlib/build/outputs/aar/testlib-debug.aar
57K	./testlib/build/outputs/aar/testlib-debugBeta.aar
52K	./testlib/build/outputs/aar/testlib-release.aar
139K	./px-testlib/build/outputs/aar/testlib-debug.aar
139K	./px-testlib/build/outputs/aar/testlib-debugBeta.aar
123K	./px-testlib/build/outputs/aar/testlib-release.aar
2.9M	./px-checkout/build/outputs/aar/checkout-release.aar
3.1M	./px-checkout/build/outputs/aar/checkout-debug.aar
3.1M	./px-checkout/build/outputs/aar/checkout-debugBeta.aar
58K	./px-addons/build/outputs/aar/addons-debug.aar
50K	./px-addons/build/outputs/aar/addons-release.aar
58K	./px-addons/build/outputs/aar/addons-debugBeta.aar

**Comment by guchito9** [comment]
396K	./px-services/build/outputs/aar/services-release.aar
483K	./px-services/build/outputs/aar/services-debugBeta.aar
483K	./px-services/build/outputs/aar/services-debug.aar
57K	./testlib/build/outputs/aar/testlib-debug.aar
57K	./testlib/build/outputs/aar/testlib-debugBeta.aar
52K	./testlib/build/outputs/aar/testlib-release.aar
139K	./px-testlib/build/outputs/aar/testlib-debug.aar
139K	./px-testlib/build/outputs/aar/testlib-debugBeta.aar
123K	./px-testlib/build/outputs/aar/testlib-release.aar
2.9M	./px-checkout/build/outputs/aar/checkout-release.aar
3.1M	./px-checkout/build/outputs/aar/checkout-debug.aar
3.1M	./px-checkout/build/outputs/aar/checkout-debugBeta.aar
58K	./px-addons/build/outputs/aar/addons-debug.aar
50K	./px-addons/build/outputs/aar/addons-release.aar
58K	./px-addons/build/outputs/aar/addons-debugBeta.aar

**Comment by guchito9** [comment]
396K	./px-services/build/outputs/aar/services-release.aar
483K	./px-services/build/outputs/aar/services-debugBeta.aar
483K	./px-services/build/outputs/aar/services-debug.aar
57K	./testlib/build/outputs/aar/testlib-debug.aar
57K	./testlib/build/outputs/aar/testlib-debugBeta.aar
52K	./testlib/build/outputs/aar/testlib-release.aar
139K	./px-testlib/build/outputs/aar/testlib-debug.aar
139K	./px-testlib/build/outputs/aar/testlib-debugBeta.aar
123K	./px-testlib/build/outputs/aar/testlib-release.aar
2.9M	./px-checkout/build/outputs/aar/checkout-release.aar
3.1M	./px-checkout/build/outputs/aar/checkout-debug.aar
3.1M	./px-checkout/build/outputs/aar/checkout-debugBeta.aar
58K	./px-addons/build/outputs/aar/addons-debug.aar
50K	./px-addons/build/outputs/aar/addons-release.aar
58K	./px-addons/build/outputs/aar/addons-debugBeta.aar

**Review by cgaggino — APPROVED** [review]

**Review by jorGonzalez291292 — APPROVED** [review]

**Comment by guchito9** [comment]
396K	./px-services/build/outputs/aar/services-release.aar
483K	./px-services/build/outputs/aar/services-debugBeta.aar
483K	./px-services/build/outputs/aar/services-debug.aar
57K	./testlib/build/outputs/aar/testlib-debug.aar
57K	./testlib/build/outputs/aar/testlib-debugBeta.aar
52K	./testlib/build/outputs/aar/testlib-release.aar
138K	./px-testlib/build/outputs/aar/testlib-debug.aar
138K	./px-testlib/build/outputs/aar/testlib-debugBeta.aar
122K	./px-testlib/build/outputs/aar/testlib-release.aar
1.8M	./px-checkout/build/outputs/aar/checkout-release.aar
2.1M	./px-checkout/build/outputs/aar/checkout-debug.aar
2.1M	./px-checkout/build/outputs/aar/checkout-debugBeta.aar
58K	./px-addons/build/outputs/aar/addons-debug.aar
50K	./px-addons/build/outputs/aar/addons-release.aar
58K	./px-addons/build/outputs/aar/addons-debugBeta.aar

**Comment by guchito9** [comment]
414K	./px-services/build/outputs/aar/services-release.aar
503K	./px-services/build/outputs/aar/services-debugBeta.aar
503K	./px-services/build/outputs/aar/services-debug.aar
57K	./testlib/build/outputs/aar/testlib-debug.aar
57K	./testlib/build/outputs/aar/testlib-debugBeta.aar
52K	./testlib/build/outputs/aar/testlib-release.aar
138K	./px-testlib/build/outputs/aar/testlib-debug.aar
138K	./px-testlib/build/outputs/aar/testlib-debugBeta.aar
122K	./px-testlib/build/outputs/aar/testlib-release.aar
1.8M	./px-checkout/build/outputs/aar/checkout-release.aar
2.0M	./px-checkout/build/outputs/aar/checkout-debug.aar
2.0M	./px-checkout/build/outputs/aar/checkout-debugBeta.aar
61K	./px-addons/build/outputs/aar/addons-debug.aar
52K	./px-addons/build/outputs/aar/addons-release.aar
61K	./px-addons/build/outputs/aar/addons-debugBeta.aar

**Pull request merged**
